# Generated by Django 3.0.6 on 2021-05-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetlist',
            options={},
        ),
        migrations.AddField(
            model_name='assetlist',
            name='Owner',
            field=models.CharField(default='MK Makerspace', help_text='Owner', max_length=50),
            preserve_default=False,
        ),
    ]
