# Generated by Django 3.0.6 on 2021-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergencyContactName',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='emergencyContactPhone',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
