# Generated by Django 3.0.6 on 2021-05-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210512_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emergencyContactName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergencyContactPhone',
        ),
    ]
