# Generated by Django 3.0.6 on 2021-05-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210512_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_Contact_Name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_Contact_Phone',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
