# Generated by Django 3.0.6 on 2021-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210513_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_mac_addresses',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
