# Generated by Django 3.0.6 on 2021-05-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_device_mac_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='device_mac_addresses',
            field=models.CharField(blank=True, help_text='By adding a MAC address you are opting in to MACScanner using your device details to monitor if you are in the space. If you do not wish for this to occur please leave the space blank. Multiple addresses can be added, comma separated.', max_length=100, verbose_name='Device MAC addresses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_Contact_Name',
            field=models.CharField(blank=True, help_text='Please supply an emergency contact, this will be used in emergencies only. If you do not have an emergency contact please leave blank.', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_Contact_Phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
